export {default as HomePage} from "./home"
export {default as LoginPage} from "./login"
export {default as ProfilePage} from "./profile"
export {default as ForgetPass} from "./forget-password"
export {default as PlantPage} from "./plant"